<a href="https://colab.research.google.com/github/Adj95/python_dsc/blob/main/Categorical_encodingh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **ENCODING CATEGORIACL DATA**


In [1]:
import numpy as np
import pandas as pd
import sklearn


In [2]:
df = pd.read_csv("/content/customer.csv")
df = df.iloc[: ,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [3]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test = train_test_split(df.drop('purchased' , axis = 1) , df['purchased'] , test_size =0.3 , random_state=0)
x_train.shape , y_train.shape , x_test.shape

((35, 2), (35,), (15, 2))

In [12]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories =[['Poor' , 'Average' , 'Good'] , ['School' , 'UG' , 'PG']])
oe.fit(x_train)
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)
x_train

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

**label** **encoding**


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

# **ONE HOT ENCODING**

In [16]:
import numpy as np
import pandas as pd

df1 = pd.read_csv("/content/cars.csv")
df1.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [17]:
df1['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test = train_test_split(df1.drop('selling_price' , axis = 1) , df1['selling_price'] , test_size =0.2 , random_state=0)
x_train

brand  km_driven    fuel         owner
3042     Hyundai      60000     LPG   First Owner
1520        Tata     150000  Diesel   Third Owner
2611     Hyundai     110000  Diesel  Second Owner
3544    Mahindra      28000  Diesel  Second Owner
4138      Maruti      15000  Petrol   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[6502 rows x 4 columns]

In [25]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop ='first')

x_train_new = ohe.fit_transform(x_train[['fuel' , 'owner']]).toarray()
x_test_new = ohe.transform(x_test[['fuel' , 'owner']]).toarray()
x_train_new.shape

(6502, 7)

In [24]:
#drops first collumn , use sparse = false so no need of toarray convert output from float to int


#from sklearn.preprocessing import OneHotEncoder
#ohe = OneHotEncoder(drop ='first' , sparse_output = False , dtype = np.int32)

#x_train_new = ohe.fit_transform(x_train[['fuel' , 'owner']])
#x_test_new = ohe.transform(x_test[['fuel' , 'owner']])
#x_train_new.shape
#x_train_new

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [26]:
np.hstack((x_train[['brand', 'km_driven']].values , x_train_new))

array([['Hyundai', 60000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 150000, 1.0, ..., 0.0, 0.0, 1.0],
       ['Hyundai', 110000, 1.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Hyundai', 90000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Volkswagen', 90000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 110000, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

removing columns with less frequency out of many variables


In [29]:
counts = df1['brand'].value_counts()
repl = counts[counts<=100].index

pd.get_dummies(df1['brand'].replace(repl , 'uncommon'))

BMW  Chevrolet   Ford  Honda  Hyundai  Mahindra  Maruti  Renault  \
0     False      False  False  False    False     False    True    False   
1     False      False  False  False    False     False   False    False   
2     False      False  False   True    False     False   False    False   
3     False      False  False  False     True     False   False    False   
4     False      False  False  False    False     False    True    False   
...     ...        ...    ...    ...      ...       ...     ...      ...   
8123  False      False  False  False     True     False   False    False   
8124  False      False  False  False     True     False   False    False   
8125  False      False  False  False    False     False    True    False   
8126  False      False  False  False    False     False   False    False   
8127  False      False  False  False    False     False   False    False   

      Skoda   Tata  Toyota  Volkswagen  uncommon  
0     False  False   False       False     False  
1      True  False   False       False     False  
2     False  False   False       False     False  
3     False  False   False       False     False  
4     False  False   False       False     False  
...     ...    ...     ...         ...       ...  
8123  False  False   False       False     False  
8124  False  False   False       False     False  
8125  False  False   False       False     False  
8126  False   True   False       False     False  
8127  False   True   False       False     False  

[8128 rows x 13 columns]

# COLUMN TRANSFORMER

In [33]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

df2 = pd.read_csv("/content/covid_toy.csv")
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test = train_test_split(df2.drop('has_covid' , axis = 1) , df2['has_covid'] , test_size =0.2 , random_state=0)
x_train

age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
96   51  Female  101.0  Strong    Kolkata
67   65    Male   99.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
47   18  Female  104.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi

[80 rows x 5 columns]

In [36]:
from sklearn.compose import ColumnTransformer
trans = ColumnTransformer( transformers = [
    ('tnf1' , OrdinalEncoder(categories = [['Mild' , 'Strong']]) ,['cough']),
    ('tnf2'  , SimpleImputer() , ['fever']),
    ('tnf3' , OneHotEncoder(drop = 'first') , ['gender' , 'city'])


] , remainder = 'passthrough')
x_train = trans.fit_transform(x_train)
x_test=trans.transform(x_test)
x_train

array([[  0.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [  1.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [  0.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [  1.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [  0.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [  1.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [  1.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  14.        ],
       [  1.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [  0.        ,  98.        ,   1.        ,   0.        ,
          1.    